### ISSUE TITLE
Hello.The method you provided does not solve this problem.

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#23]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/141488c4-e2ba-4518-8f56-a4f40d2ef9c3)
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/3fd4903e-da88-43dd-afc6-e7f55922bfba)
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/ef1bb826-20f2-45ae-982e-4ce0b26976b2)

**Comment by rahulbera** [comment]
Hi @szuhzw, the rate and the way you are describing the issue is not helpful for anyone because of multiple reasons:

1. You are not mentioning any observation/data necessary to resolve the error you are facing apart from saying "this is not working". This does not convey any meaningful information regarding: 

- Which machine you are using to run the script? Which McPAT version you are using? How did you compile?
- Is only a few McPAT runs are not working or all of them are not working?
- Is the run stuck and not progressing? Or did it show any error message?
- Have you at all tried to debug it by yourself before raising the issue in GitHub? A simple debug can be just to put print statements in multiple places to narrow down where exactly McPAT is getting stuck. This is debugging-101 and should give some meaningful information for us to debug your case.

Without any such information and multiple GitHub issues in a close succession, I hate to say but it becomes a bit annoying to some extent, which does not ultimately help any party here.

2. We, the maintainers of this repository, have other research/tasks to manage too. So if you are not getting the reply immediately, please have some patience and wait till we get back to you.

---

Now since I do not have any other information to me than just *"Hello.The method you provided does not solve this problem"*, please clone the following repository (https://github.com/rahulbera/Hermes-McPAT) and compile McPAT. This one should already have non-power-of-2 cache associativity modelled. I have also provided the XML files that I have used for Hermes's power analysis inside the `hermes_eval` directory (note that, these files already have the appropriate core/cache/memory statistics embedded inside them to drive the power model). 

After you compile McPAT, you should see `mcpat` executable in the home directory. Please try executing `./mcpat -infile Hermes_eval/<any XML file>` to check whether it's working. I just ran it in my local machine (Intel Xeon 5118, Ubuntu 22.04, gcc 11.3.0), and it generates result within 10 seconds.

If this still does not run in your machine, then please first try to debug it by yourself and then post here with some meaningful debugging information.

**Comment by konkanello** [comment]
@rahulbera I am facing similar issues.

**Comment by hhulll** [comment]
Thank you for your help.

**Comment by szuhzw** [comment]
Hello. What metrics are used to analyze the performance of eight-core system in the article? Is it the average IPC for eight cores? @rahulbera

**Comment by szuhzw** [comment]
Hello.Could you resolve my question? What metrics are used to analyze the performance of eight-core system in the article? Is it the average IPC for eight cores? @rahulbera

**Comment by szuhzw** [comment]
Hello. Could you resolve my question? What metrics are used to analyze the performance of eight-core system in the article? Is it the average IPC for eight cores? @rahulbera

**Comment by rahulbera** [comment]
Hi @szuhzw, we use the geomean IPC of all eight cores as the performance metric to evaluate the speedup of each techniques.

**Comment by szuhzw** [comment]
Hello. I've been running this for 2 hours and still no results (12th Gen Intel(R) Core(TM) i7-12700, Ubuntu 22.04.3 LTS, gcc 11.4.0). Do I need to wait any longer? @rahulbera 
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/10e33a95-bf4e-47c2-8672-ede1894acfe1)

**Comment by konkanello** [comment]
I have the same issue. It's better to wait more. It would also be better running in a more powerful core.

**Comment by szuhzw** [comment]
Hello. Did you finally successfully generate the result? 

> [konkanello](/konkanello)

**Comment by szuhzw** [comment]
Hello. I've been running this for 22 hours and still no results (12th Gen Intel(R) Core(TM) i7-12700, Ubuntu 22.04.3 LTS, gcc 11.4.0).

**Comment by szuhzw** [comment]
Hello. I've been running this for 22 hours and still no results (12th Gen Intel(R) Core(TM) i7-12700, Ubuntu 22.04.3 LTS, gcc 11.4.0). Do I need to wait any longer? 
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/8418f6ea-e8d3-4e81-9d37-f7bd720f2b6b)
